#!/bin/bash

# make sure db and cache are running, just in case of restarts
sudo service mariadb start
sudo service redis-server start

# this seems to more reliably get the private proxy working
sudo apache2ctl stop
sudo apache2ctl start

# Run local devcontainer lifecycle scripts
if [ -x .devcontainer/postStart.sh ]; then
  .devcontainer/postStart.sh
fi