#!/bin/bash

# this seems to be necessary to reliably get the codespace private proxy working
sudo apache2ctl stop
sleep 1 # wait for apache to stop
sudo apache2ctl start

# Run local devcontainer lifecycle scripts
if [ -x .devcontainer/postStart.sh ]; then
  .devcontainer/postStart.sh
fi