#!/bin/bash

# Authenticate to Pantheon iff the user set a token env var
if [[ -n "$TERMINUS_TOKEN" ]]; then
  terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
fi

# Tnstall GitHub CLI Copilot Extension
if [[ -n "$GH_TOKEN" ]] || [[ -n "$GITHUB_TOKEN" ]] ; then
  gh extension install github/gh-copilot
fi

# set global ServerName so that apachectl isn't chatty
if [[ -n "$CODESPACE_NAME" ]]; then
  SERVER_NAME="$CODESPACE_NAME-8080.app.github.dev"
  HTTP_ADDRESS="$SERVER_NAME"
else
  SERVER_NAME="localhost"
  HTTP_ADDRESS="$SERVER_NAME:8080"
fi
echo "ServerName $SERVER_NAME" | sudo tee /etc/apache2/conf-available/global-servername.conf
sudo a2enconf global-servername

# Setup drush
mkdir -p drush
export HTTP_ADDRESS
build/templater.sh /usr/local/etc/uceap-dev/example.drush.yml > drush/drush.yml

# Run local devcontainer lifecycle scripts
if [ -x .devcontainer/postCreate.sh ]; then
  .devcontainer/postCreate.sh
fi