#!/bin/bash
set -eo pipefail

# ensure we're working in the workspace folder
if [ -n "$WORKSPACE_FOLDER" ]; then
  cd $WORKSPACE_FOLDER
else
  echo "No WORKSPACE_FOLDER environment variable set, please update your devcontainer.json file."
  # as a transitional fallback, check to see if composer.json exists in the current directory, in which case we assume we're in the workspace folder
  if [ ! -f composer.json ]; then
    echo "No composer.json found in the current directory, please run this script from the root of your project."
    exit 1
  fi
fi

# during first run, the new PATH from the on-create script is not yet in effect
if ( ! command -v drush > /dev/null ); then
  export PATH="`pwd`/vendor/bin:$PATH"
fi

# the first time we run this script the default umask is still in effect,
# which messes up permissions on the profiler directory that gets created when the caches are rebuilt by db-rebuild.sh
umask 002

# Run local devcontainer lifecycle scripts
if [ -x .devcontainer/updateContent.sh ]; then
  .devcontainer/updateContent.sh
fi