#!/bin/bash
set -eo pipefail

# Change default umask and add user to web group so we can share write permission on web files
sed -i 's/^#umask\s*022/umask 002/' ~/.profile
echo "umask 002" >> ~/.zshrc
echo "umask 002" >> ~/.bashrc

sudo sh -c "cat >> /etc/apache2/sites-available/000-default.conf" <<EOF
<Directory /var/www/html>
  AllowOverride All
</Directory>
EOF

# This is how the example codespace changes the docroot. If it's good enough for them, it's good enough for me.
sudo chmod a+x "$(pwd)" && sudo rm -rf /var/www/html && sudo ln -s "$(pwd)/web" /var/www/html

# Setup database
sudo service mariadb start
sudo mysql -u$MYSQL_USER -e "SET PASSWORD=PASSWORD('$MYSQL_PASSWORD')"
cat <<EOF > ~/.my.cnf
[client]
user="$MYSQL_USER"
password="$MYSQL_PASSWORD"
EOF
mysqladmin create $MYSQL_DATABASE

# and cache
sudo service redis-server start

# translate mysql env vars to our template vars
export DB_HOST="$MYSQL_HOST" DB_PORT="$MYSQL_TCP_PORT" DB_USER="$MYSQL_USER" DB_PASSWORD="$MYSQL_PASSWORD" DB_NAME="$MYSQL_DATABASE"

# Setup our Drupal app
composer dev-initialize-local
cat >> web/sites/default/settings.local.php <<EOF
\$settings['trusted_host_patterns'] = [];

# make drupal play nice with codespace proxy
\$settings['reverse_proxy'] = TRUE;
\$settings['reverse_proxy_addresses'] = array(\$_SERVER['REMOTE_ADDR']);
EOF

composer install
composer compile-theme

# Set file permissions so both httpd and user can write to files
chgrp www-data web/sites/default/files
chmod g+s web/sites/default/files

# Setup VS Code
mkdir -p .vscode
cp /usr/local/etc/uceap-dev/vscode-launch.json .vscode/launch.json
