#!/bin/bash
set -eo pipefail

# re-run composer install (e.g. in case we've switched branches since last time we ran this script)
composer install

# during first run, the new PATH from the on-create script is not yet in effect
if ( ! command -v drush > /dev/null ); then
  export PATH="`pwd`/vendor/bin:$PATH"
fi

# we need to preserve gitconfig if it already exists
if [ -f ~/.gitconfig ]; then
  gitconfig_existed=true
fi
# ownership of the workspace directory won't match when using bindfs
git config --global --add safe.directory "$(pwd)"
# gh runs git, so we need to set the safe.directory in order for it to work
gh release download --clobber --pattern '*.gz'
# but later on vscode will try setting global git config (credential helper, etc) ONLY if gitconfig doesn't exist
if [ ! $gitconfig_existed ]; then
  rm ~/.gitconfig
fi
# FWIW vscode will also fix the safe.directory setting

tar zx --no-same-permissions --strip-components 1 -C web/sites/default/files -f files.tar.gz
rm files.tar.gz

# no-same-permissions doesn't seem to work so we fix it here
sudo find web/sites/default/files -type d -exec chmod g+ws {} +
sudo find web/sites/default/files -type f -exec chmod g+w {} +

# the first time we run this script the default umask is still in effect,
# which messes up permissions on the profiler directory that gets created when the caches are rebuilt by db-rebuild.sh
umask 002

sudo service mariadb start
build/db-rebuild.sh database.sql.gz
rm database.sql.gz

# Run local devcontainer lifecycle scripts
if [ -x .devcontainer/updateContent.sh ]; then
  .devcontainer/updateContent.sh
fi