#!/bin/bash
set -eo pipefail

# ensure we're working in the workspace folder
if [ -n "$WORKSPACE_FOLDER" ]; then
  cd $WORKSPACE_FOLDER
else
  echo "No WORKSPACE_FOLDER environment variable set, please update your devcontainer.json file."
  # as a transitional fallback, check to see if composer.json exists in the current directory, in which case we assume we're in the workspace folder
  if [ ! -f composer.json ]; then
    echo "No composer.json found in the current directory, please run this script from the root of your project."
    exit 1
  fi
fi

# re-run composer install (e.g. in case we've switched branches since last time we ran this script)
composer install

# re-build the theme (likewise in case of changes)
composer compile-theme

# during first run, the new PATH from the on-create script is not yet in effect
if ( ! command -v drush > /dev/null ); then
  export PATH="`pwd`/vendor/bin:$PATH"
fi

# FIXME
# this script used to download database/files from github packages
# now we need to download from pantheon backups instead
# tar zx --no-same-permissions --strip-components 1 -C web/sites/default/files -f files.tar.gz
# rm files.tar.gz

# # no-same-permissions doesn't seem to work so we fix it here
# sudo find web/sites/default/files -type d -exec chmod g+ws {} +
# sudo find web/sites/default/files -type f -exec chmod g+w {} +

# the first time we run this script the default umask is still in effect,
# which messes up permissions on the profiler directory that gets created when the caches are rebuilt by db-rebuild.sh
umask 002

sudo service mariadb start
# build/db-rebuild.sh database.sql.gz
# rm database.sql.gz

# Run local devcontainer lifecycle scripts
if [ -x .devcontainer/updateContent.sh ]; then
  .devcontainer/updateContent.sh
fi